---
title             : "Evidence weighting in confidence judgments for detection and discrimination"
shorttitle        : "Evidence weighting in confidence judgments for detection and discrimination"

author: 
  - name          : "Matan Mazor"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "12 Queen Square, London WC1N 3BG"
    email         : "mtnmzor@gmail.com"
  - name          : "Lucie Charles"
    affiliation   : "4"
  - name          : "Roni Maimon-Mor"
    affiliation   : "4,5" 
  - name          : "Stephen M. Fleming"
    affiliation   : "1,2,3"

affiliation:
  - id            : "1"
    institution   : "Wellcome Centre for Human Neuroimaging, UCL"
  - id            : "2"
    institution   : "Max Planck UCL Centre for Computational Psychiatry and Ageing Research"
  - id            : "3"
    institution   : "Department of Experimental Psychology, UCL"
  - id            : "4"
    institution   : "Institute of Cognitive Neuroscience, UCL"
  - id            : "5"
    institution   : "FMRIB Centre, Nuffield Department of Clinical Neuroscience, University of Oxford"

authornote: |
  The authors have no conflicting interests to declare.

abstract: | 
  Confidence in perceptual decisions is more sensitive to evidence in support of the decision than to evidence against it. This positive evidence bias (PEB) has been demonstrated in confidence ratings in binary discrimination decisions between two stimulus categories. Recent theoretical proposals suggest that a PEB is due to observers adopting a detection-like strategy when rating their confidence, one that has functional benefits for metacognition in real-world settings where detectability and discriminability often go hand in hand. However, it is unknown whether, or how, a PEB is also in play for detection decisions about the presence or absence of a stimulus. In three experiments (one lab-based and two online) we first successfully replicate a PEB in discrimination confidence. We then show that a PEB is observed in detection decisions, where participants report the presence or absence of a stimulus, regardless of its identity. We discuss our findings in relation to models that account for a positive evidence bias as emerging from a confidence-specific heuristic, and alternative models where decision and confidence are generated by the same, Bayes-rational process.

  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "confidence, detection, metacognition"
wordcount         : "X"

bibliography      : ["RC.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_word


---
# Compuatational models

## General framework

### Generative model {-}

Stimuli were represented as two vectors of 12 values each {\vec{E}_l} and {\vec{E}_r}, corresponding to the two sensory channels (e.g., the right and left stimuli in Exp. 2). In the discrimination task, one sensory channel transmitted pure noise (that is, samples were centered around zero), and one channel had additional signal in it (samples were centered around a non-zero value). The signal channel was chosen randomly for each trial with equal probability. In the detection task, both sensory channels transmitted pure noise. 

\begin{equation}
  E[i] \sim \begin{cases}
    \mathcal{N}(0.5,1), & \text{if signal}.\\
    \mathcal{N}(0,1), & \text{if noise}.\\
  \end{cases}
\end{equation}

On top of the presented noise, we added perceptual noise to the stimulus, resulting in a degraded representation of each sensory channel $E'$. Importantly, this additional noise affected the agent's decisions and confidence ratings, but did not affect the stimulus itself such that trial-wise estimates of stimulus energy were unaffected for the reverse correlation analysis.  The noise was channel and time specific.

### Belief update {-}

Agents kept track of three quantities, the log likelihood for signal in the right versus the left channels ($LLR_r$), and the log likelihood for the presence of signal in one of the channels, versus noise in both channels ($LLR_p$). Both values were set to 0 at the beginning of each trial. They were then updated from the second timepoint and on (we used the first timepoint as a control, to make sure reverse correlation analysis is not showing any effect of evidence at this timepoint). Log likelihood ratios were updated according to the following rule:

$$
 LLR_{r,i+1} = LLR_{r,i}+log(P_s(E'_r{i})+log(P_n(E'_l{i})) - log(P_n(E'_r{i})-log(P_s(E'_l{i}))
$$ 

and 

$$ LLR_{p,i+1} = LLR_{p,i} + log(p_{right}P_s(E'_r{i})P_n(E'_l{i})+p_{left}P_n(E'_r{i})P_s(E'_l{i})) - log(P_n(E'_r{i}))-log(P_n(E'_l{i}))
$$
where $P_s$ is the true probability density function of $E'$ values conditioned on signal being present in the channel, and $P_n$ is the true probability density function of $E'$ values conditioned on signal being absent. $p_{right}=\frac{e^{LLR_{r,i}}}{1+e^{LLR_{r,i}}}$ is the probability that the signal is in the right channel (based on all previous samples) and $p_{left}=1-p_{right}$ is the probability that the signal is in the left channel (conditioned on signal presence). Note that subjects are rationally incorporating accurate beliefs about the effect of sensory noise on evidence strength in updating their beliefs about the world state.

### Decision {-}

In discrimination, agents decided 'right' when $LLR_r>0$ and 'left' otherwise. In detection, agents decided 'present' when $LLR_p>0$ and 'absent' otherwise.

### Confidence {-}

Confidence was the probability of being correct, given an equal prior over the two world states. This equals $\frac{e^{LLR_{r}}}{1+e^{LLR_{r}}}$ in discrimination and $\frac{e^{LLR_{p}}}{1+e^{LLR_{p}}}$ in detection.

## Vanilla

In the vanilla model, sensory noise was sampled from $\mathcal{N}(0,2)$.

A python simulation is available [in the project's GitHub](https://github.com/matanmazor/reverseCorrelation/blob/main/simulations/equal_variance.ipynb).

## Stimulus-dependent noise

In the stimulus-dependent noise model, sensory noise was sampled from $\mathcal{N}(0,2^{E})$.

A python simulation is available [in the project's GitHub](https://github.com/matanmazor/reverseCorrelation/blob/main/simulations/unequal_variance.ipynb).

## Random attention

In the random attention noise model, sensory noise was sampled from $\mathcal{N}(0,2)$. However, subjects had only access to one sensory channel per timepoint. 

At the beginning of each trial, one of the two channels was chosen at random with equal probability to be the preferred channel. Then, at each timepoint, one of the two channels was selected to be attended, with a $0.95$ probability of being the preferred channel. Subjects then used information from this channel only to update their beliefs. For example, upon attending the left channel:


$$
 LLR_{r,i+1} = LLR_{r,i}+log(P_n(E'_l{i})) - log(P_s(E'_l{i}))
$$ 

and 

$$ LLR_{p,i+1} = LLR_{p,i} + log(p_{right}P_n(E'_l{i})+p_{left}P_s(E'_l{i})) - log(P_n(E'_l{i}))
$$


A python simulation is available [in the project's GitHub](https://github.com/matanmazor/reverseCorrelation/blob/main/simulations/random_attention.ipynb).

## Goal-directed attention

In the goal-directed attention noise model, sensory noise was sampled from $\mathcal{N}(0,2)$. However, subjects had only access to one sensory channel per timepoint. 

The probability of attending the right channel was set to $S(LLR_r)$, where $S(x)=\frac{1}{1+e^{-5x}}$. This made agents heavily biased to attend the channel that is more likely to include signal. 


A python simulation is available [in the project's GitHub](https://github.com/matanmazor/reverseCorrelation/blob/main/simulations/goal_directed_attention.ipynb).
